const ICON_SIZE = 30.0;
const SMALL_ICON_SIZE = 18.0;
const PARAGRAPH_FONT_SIZE = 14.0;
const HEADING_FONT_SIZE = 28.0;
const SMALL_HEADING_FONT_SIZE = 18.0;
const LOADING_TITLE_FONT_SIZE = 36.0;
const TITLE_FONT_SIZE = 28.0;
